# cython: language_level=3
import cython
from sqlcycli.constants import CLIENT

# https://dev.mysql.com/doc/internals/en/capability-flags.html#packet-Protocol::CapabilityFlags
LONG_PASSWORD: cython.uint = CLIENT.LONG_PASSWORD
FOUND_ROWS: cython.uint = CLIENT.FOUND_ROWS
LONG_FLAG: cython.uint = CLIENT.LONG_FLAG
CONNECT_WITH_DB: cython.uint = CLIENT.CONNECT_WITH_DB
NO_SCHEMA: cython.uint = CLIENT.NO_SCHEMA
COMPRESS: cython.uint = CLIENT.COMPRESS
ODBC: cython.uint = CLIENT.ODBC
LOCAL_FILES: cython.uint = CLIENT.LOCAL_FILES
IGNORE_SPACE: cython.uint = CLIENT.IGNORE_SPACE
PROTOCOL_41: cython.uint = CLIENT.PROTOCOL_41
INTERACTIVE: cython.uint = CLIENT.INTERACTIVE
SSL: cython.uint = CLIENT.SSL
IGNORE_SIGPIPE: cython.uint = CLIENT.IGNORE_SIGPIPE
TRANSACTIONS: cython.uint = CLIENT.TRANSACTIONS
SECURE_CONNECTION: cython.uint = CLIENT.SECURE_CONNECTION
MULTI_STATEMENTS: cython.uint = CLIENT.MULTI_STATEMENTS
MULTI_RESULTS: cython.uint = CLIENT.MULTI_RESULTS
PS_MULTI_RESULTS: cython.uint = CLIENT.PS_MULTI_RESULTS
PLUGIN_AUTH: cython.uint = CLIENT.PLUGIN_AUTH
CONNECT_ATTRS: cython.uint = CLIENT.CONNECT_ATTRS
PLUGIN_AUTH_LENENC_CLIENT_DATA: cython.uint = CLIENT.PLUGIN_AUTH_LENENC_CLIENT_DATA
CAPABILITIES: cython.uint = CLIENT.CAPABILITIES

# Not done yet
HANDLE_EXPIRED_PASSWORDS: cython.uint = CLIENT.HANDLE_EXPIRED_PASSWORDS
SESSION_TRACK: cython.uint = CLIENT.SESSION_TRACK
DEPRECATE_EOF: cython.uint = CLIENT.DEPRECATE_EOF
