# cython: language_level=3

cdef:
    unsigned int LONG_PASSWORD, FOUND_ROWS, LONG_FLAG, CONNECT_WITH_DB
    unsigned int NO_SCHEMA, COMPRESS, ODBC, LOCAL_FILES, IGNORE_SPACE
    unsigned int PROTOCOL_41, INTERACTIVE, SSL, IGNORE_SIGPIPE
    unsigned int TRANSACTIONS, SECURE_CONNECTION, MULTI_STATEMENTS
    unsigned int MULTI_RESULTS, PS_MULTI_RESULTS, PLUGIN_AUTH
    unsigned int CONNECT_ATTRS, PLUGIN_AUTH_LENENC_CLIENT_DATA, CAPABILITIES
