# cython: language_level=3
import cython
from sqlcycli.constants import SERVER_STATUS

# fmt: off
SERVER_STATUS_IN_TRANS: cython.uint = SERVER_STATUS.SERVER_STATUS_IN_TRANS
SERVER_STATUS_AUTOCOMMIT: cython.uint = SERVER_STATUS.SERVER_STATUS_AUTOCOMMIT
SERVER_MORE_RESULTS_EXISTS: cython.uint = SERVER_STATUS.SERVER_MORE_RESULTS_EXISTS
SERVER_QUERY_NO_GOOD_INDEX_USED: cython.uint = SERVER_STATUS.SERVER_QUERY_NO_GOOD_INDEX_USED
SERVER_QUERY_NO_INDEX_USED: cython.uint = SERVER_STATUS.SERVER_QUERY_NO_INDEX_USED
SERVER_STATUS_CURSOR_EXISTS: cython.uint = SERVER_STATUS.SERVER_STATUS_CURSOR_EXISTS
SERVER_STATUS_LAST_ROW_SENT: cython.uint = SERVER_STATUS.SERVER_STATUS_LAST_ROW_SENT
SERVER_STATUS_DB_DROPPED: cython.uint = SERVER_STATUS.SERVER_STATUS_DB_DROPPED
SERVER_STATUS_NO_BACKSLASH_ESCAPES: cython.uint = SERVER_STATUS.SERVER_STATUS_NO_BACKSLASH_ESCAPES
SERVER_STATUS_METADATA_CHANGED: cython.uint = SERVER_STATUS.SERVER_STATUS_METADATA_CHANGED
# fmt: on
